name: MOM_interface CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "ci" ]

jobs:
  ci_tests:
    name: MOM_interface CI tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Install Ubuntu linux packages
        run: |
          echo "::group::Install linux packages"
          sudo apt-get update
          sudo apt-get install netcdf-bin
          sudo apt-get install libnetcdf-dev
          sudo apt-get install libnetcdff-dev
          sudo apt-get install openmpi-bin
          sudo apt-get install libopenmpi-dev
          sudo apt-get install linux-tools-common
          echo "::endgroup::"

    
      # clone CESM
      - uses: actions/checkout@v4
        with:
          repository: ESCOMP/CESM
          ref: cesm3_0_alpha03a
          #submodules: recursive

      - name: Run git-fleximod
        run: |
          ./bin/git-fleximod update
      
      - name: Build standalone mom6
        run: |
          cd components/mom/standalone/build
          git remote add altuntas https://github.com/alperaltuntas/MOM_interface.git
          git checkout altuntas/ci
          ./build_examples-ncar.sh --compiler gnu
